<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ImageClassifier.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Models\Prism.Core.Contracts.csproj" />
  </ItemGroup>
</Project>
