<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="IImageTransformation.cs" />
    <Compile Include="ImageTransformer.cs" />
    <Compile Include="Tx_CenterAndStretch.cs" />
    <Compile Include="Tx_CropSquare.cs" />
    <Compile Include="Tx_DetailCropper.cs" />
    <Compile Include="Tx_ProblemImageProcessor.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Models\Prism.Core.Contracts.csproj" />
  </ItemGroup>
</Project>
