<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Prism.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="IImageTransformation.cs" />
    <Compile Include="..\ImageTransformer.cs" />
    <Compile Include="Tx_CenterAndStretch.cs" />
    <Compile Include="Tx_CropSquare.cs" />
    <Compile Include="Tx_DetailCropper.cs" />
    <Compile Include="Tx_ProblemImageProcessor.cs" />
    <Compile Include="Tx_util_BgStretch.cs" />
    <Compile Include="Tx_util_HeadCutter.cs" />
    <Compile Include="Utils\Tx_LowContrastEnhancement.cs" />
    <Compile Include="..\Admin\AssemblyInfo.cs" Link="Admin\AssemblyInfo.cs" />
    <Compile Include="..\Admin\TransformParameters.cs" Link="Admin\TransformParameters.cs" />
    <Compile Include="..\Admin\CropTransformSettings.cs" Link="Admin\CropTransformSettings.cs" />
    <Compile Include="..\Admin\ProblemImageProcessorConfig.cs" Link="Admin\ProblemImageProcessorConfig.cs" />
    <Compile Include="..\Admin\BgStretchConfig.cs" Link="Admin\BgStretchConfig.cs" />
    <Compile Include="..\Admin\DetailCropperConfig.cs" Link="Admin\DetailCropperConfig.cs" />
    <Compile Include="..\Admin\LowContrastEnhancementConfig.cs" Link="Admin\LowContrastEnhancementConfig.cs" />
    <Compile Include="..\Admin\HeadCutterConfig.cs" Link="Admin\HeadCutterConfig.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.10.0.20241108" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.10.0.20241108" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Models\Prism.Core.Contracts.csproj" />
  </ItemGroup>
</Project>
