<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Prism.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="AssemblyInfo.cs" />
    <Compile Include="CropTransformSettings.cs" />
    <Compile Include="IImageTransformation.cs" />
    <Compile Include="..\ImageTransformer.cs" />
    <Compile Include="Tx_CenterAndStretch.cs" />
    <Compile Include="Tx_CropSquare.cs" />
    <Compile Include="Tx_DetailCropper.cs" />
    <Compile Include="Tx_ProblemImageProcessor.cs" />
    <Compile Include="Tx_util_BgStretch.cs" />
    <Compile Include="Tx_util_HeadCutter.cs" />
    <Compile Include="Utils\Tx_LowContrastEnhancement.cs" />
    <Compile Include="TransformConfig.cs" />
    <Compile Include="ProblemImageProcessorConfig.cs" />
    <Compile Include="BgStretchConfig.cs" />
    <Compile Include="DetailCropperConfig.cs" />
    <Compile Include="LowContrastEnhancementConfig.cs" />
    <Compile Include="HeadCutterConfig.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.10.0.20241108" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.10.0.20241108" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Models\Prism.Core.Contracts.csproj" />
  </ItemGroup>
</Project>
