<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="GenerationRouteState.cs" />
    <Compile Include="ImageRecord_Base.cs" />
    <Compile Include="ImageRecord_GENERATED.cs" />
    <Compile Include="ImageRecord_INPUT.cs" />
    <Compile Include="ImageRecord_LAMBDA.cs" />
    <Compile Include="ImageRecord_OUTPUT.cs" />
    <Compile Include="PrismJobRequest.cs" />
    <Compile Include="PrismJobResult.cs" />
    <Compile Include="PrismProcessingParameters.cs" />
    <Compile Include="..\Excel\FamilyRecord.cs" Link="FamilyRecord.cs" />
    <Compile Include="..\ImageNGP\ImageNGP.cs" Link="ImageNGP.cs" />
    <Compile Include="..\IO\BatchManifest.cs" Link="BatchManifest.cs" />
    <Compile Include="..\IO\BatchManifestSummary.cs" Link="BatchManifestSummary.cs" />
    <Compile Include="..\IO\ManifestImageRow.cs" Link="ManifestImageRow.cs" />
    <Compile Include="..\Pipeline\PipelineProgressEvent.cs" Link="PipelineProgressEvent.cs" />
    <Compile Include="..\Images\Classify\ClassificationToken.cs" Link="ClassificationToken.cs" />
    <Compile Include="..\Images\Classify\EdgeIntersectionResult.cs" Link="EdgeIntersectionResult.cs" />
    <Compile Include="..\Images\Classify\ImageFeatureValue.cs" Link="ImageFeatureValue.cs" />
    <Compile Include="..\Images\Classify\ImageFeatureSnapshot.cs" Link="ImageFeatureSnapshot.cs" />
    <Compile Include="..\Images\Match\MatchEvidence.cs" Link="MatchEvidence.cs" />
    <Compile Include="..\Images\Order\OrderEvidence.cs" Link="OrderEvidence.cs" />
<Compile Include="..\Images\Transform\BackgroundType.cs" Link="BackgroundType.cs" />
    <Compile Include="..\Images\Transform\BoundingBox.cs" Link="BoundingBox.cs" />
    <Compile Include="..\Images\Transform\ImageTransformationResult.cs" Link="ImageTransformationResult.cs" />
    <Compile Include="..\Images\Transform\TransformationStatus.cs" Link="TransformationStatus.cs" />
  </ItemGroup>
</Project>
