<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Prism.Services.Matching" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\ImageUpscaler.cs" />
    <Compile Include="..\..\Matching\GpuProbe.cs" />
    <Compile Include="AssemblyInfo.cs" />
    <Compile Include="Upscaler_c_p_u.cs" />
    <Compile Include="Upscaler_g_p_u.cs" />
    <Compile Include="UpscaleConfig.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.24.4" />
    <PackageReference Include="OpenCvSharp4" Version="4.10.0.20241108" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.10.0.20241108" />
  </ItemGroup>
</Project>
